version: "3"

x-kong-config: &kong-env
  KONG_PROXY_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_PROXY_ERROR_LOG: /dev/stderr
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_ADMIN_LISTEN: 0.0.0.0:8001

x-kong-shared: &kong-shared
  image: kong/kong-gateway:3.3.0.0
  ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
    - 8444:8444
    - 8002:8002
    - 8445:8445
    - 8003:8003
    - 8004:8004

services:
  kong-dbless:
    <<: *kong-shared
    profiles: ["dbless"]
    volumes:
      - "$PWD:/kong/declarative"
    environment:
      <<: *kong-env
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml

  kong-gateway:
    <<: *kong-shared
    profiles: ["db"]
    environment:
      <<: *kong-env
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
    depends_on:
      - kong-database

  kong-database:
    image: postgres
    profiles: ["db"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "$PWD/postgres-data:/var/lib/postgresql/data"

  stonk-netcat:
    build:
      context: .
      dockerfile: Dockerfile.netcat
    profiles: ["db", "dbless"]
    ports:
      - 4444:4444
